### PR TITLE
Move to typescript to make work from typescript as well as normal node

### PR DESCRIPTION
**Pull request by lekkimworld**
I have been using the library for a while but after my move to typescript and es6 modules I couldn't make it work anymore so I converted the source to typescript to make it work as well as provide types. I wanted to provide it back to you in case you would like to adopt this. If not I'll just continue using my own fork.

The tests are passing but the source could probably be cleaned a bit. If you would like to merge this PR let me know and I'll do that before you merge.

Thank you for building this.

### CODE REVIEW

**Comment by lekkimworld** [comment]
I just published this module under `@lekkim/nordpool` on npm if you would like to try it out.

**Review by samuelmr — APPROVED** [review]
Should also increment version in package.json.

Major increment IMO.

I'll bump to 5.0.0.

**Comment by lekkimworld** [comment]
Maybe it's just me but I never check in generated assets into git so the `lib` folder that has the compiled source and types are not in npm package you uploaded as v 5.0.0. I suggest you checkout the source and do a `npm run build` and then republish the package to npm. Sorry about that.

**Comment by samuelmr** [comment]
It seems you wrote your comment just after I had done `npm run build` and published 5.0.1 :)

**Pull request merged**
